package db

var mysqlCreateTables = []string{
	`CREATE TABLE IF NOT EXISTS watch_folders (
			id INT AUTO_INCREMENT PRIMARY KEY,
			folder_path VARCHAR(500) NOT NULL UNIQUE,
			media_type ENUM('video', 'audio') NOT NULL,
			target_resolution VARCHAR(20),
			custom_ffmpeg_flags TEXT,
			enabled BOOLEAN NOT NULL DEFAULT TRUE,
			video_codec VARCHAR(32) NOT NULL DEFAULT 'libx265',
			audio_codec VARCHAR(32) NOT NULL DEFAULT 'copy',
			crf VARCHAR(8) NULL,
			preset VARCHAR(32) NULL,
			tune VARCHAR(32) NULL,
			profile VARCHAR(32) NULL,
			container VARCHAR(8) NOT NULL DEFAULT 'mkv',
			output_dir VARCHAR(500) NULL,
			delete_source BOOLEAN NOT NULL DEFAULT FALSE,
			keep_original_if_larger BOOLEAN NOT NULL DEFAULT FALSE,
			keep_extra_streams BOOLEAN NOT NULL DEFAULT TRUE,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		)`,
	`CREATE TABLE IF NOT EXISTS jobs (
			id INT AUTO_INCREMENT PRIMARY KEY,
			file_path VARCHAR(500) NOT NULL,
			media_type ENUM('video', 'audio') NOT NULL,
			status ENUM('pending', 'processing', 'failed') NOT NULL DEFAULT 'pending',
			priority INT NOT NULL DEFAULT 0,
			original_size BIGINT DEFAULT 0,
			target_resolution VARCHAR(20),
			ffmpeg_flags TEXT,
			error_message TEXT,
			video_codec VARCHAR(32) NOT NULL DEFAULT 'libx265',
			audio_codec VARCHAR(32) NOT NULL DEFAULT 'copy',
			crf VARCHAR(8) NULL,
			preset VARCHAR(32) NULL,
			tune VARCHAR(32) NULL,
			profile VARCHAR(32) NULL,
			container VARCHAR(8) NOT NULL DEFAULT 'mkv',
			output_dir VARCHAR(500) NULL,
			delete_source BOOLEAN NOT NULL DEFAULT FALSE,
			keep_original_if_larger BOOLEAN NOT NULL DEFAULT FALSE,
			keep_extra_streams BOOLEAN NOT NULL DEFAULT TRUE,
			force BOOLEAN NOT NULL DEFAULT FALSE,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		)`,
	`CREATE TABLE IF NOT EXISTS job_reports (
			id INT AUTO_INCREMENT PRIMARY KEY,
			file_path VARCHAR(500) NOT NULL,
			media_type ENUM('video', 'audio') NOT NULL,
			status ENUM('success', 'failed', 'skipped') NOT NULL,
			original_size BIGINT NOT NULL DEFAULT 0,
			encoded_size BIGINT NOT NULL DEFAULT 0,
			size_saved BIGINT NOT NULL DEFAULT 0,
			processing_time DECIMAL(10,2) DEFAULT 0,
			target_resolution VARCHAR(20),
			ffmpeg_flags TEXT,
			error_message TEXT,
			video_codec VARCHAR(32) NOT NULL DEFAULT 'libx265',
			audio_codec VARCHAR(32) NOT NULL DEFAULT 'copy',
			crf VARCHAR(8) NULL,
			preset VARCHAR(32) NULL,
			tune VARCHAR(32) NULL,
			profile VARCHAR(32) NULL,
			container VARCHAR(8) NOT NULL DEFAULT 'mkv',
			output_dir VARCHAR(500) NULL,
			delete_source BOOLEAN NOT NULL DEFAULT FALSE,
			keep_original_if_larger BOOLEAN NOT NULL DEFAULT FALSE,
			keep_extra_streams BOOLEAN NOT NULL DEFAULT TRUE,
			ffmpeg_command TEXT,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)`,
	`CREATE TABLE IF NOT EXISTS app_config (
			config_key VARCHAR(100) PRIMARY KEY,
			config_value TEXT
		)`,
}

var sqliteCreateTables = []string{
	`CREATE TABLE IF NOT EXISTS watch_folders (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			folder_path TEXT NOT NULL UNIQUE,
			media_type TEXT NOT NULL,
			target_resolution TEXT,
			custom_ffmpeg_flags TEXT,
			enabled INTEGER NOT NULL DEFAULT 1,
			video_codec TEXT NOT NULL DEFAULT 'libx265',
			audio_codec TEXT NOT NULL DEFAULT 'copy',
			crf TEXT,
			preset TEXT,
			tune TEXT,
			profile TEXT,
			container TEXT NOT NULL DEFAULT 'mkv',
			output_dir TEXT,
			delete_source INTEGER NOT NULL DEFAULT 0,
			keep_original_if_larger INTEGER NOT NULL DEFAULT 0,
			keep_extra_streams INTEGER NOT NULL DEFAULT 1,
			created_at DATETIME NOT NULL DEFAULT (datetime('now')),
			updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
		)`,
	`CREATE TABLE IF NOT EXISTS jobs (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			file_path TEXT NOT NULL,
			media_type TEXT NOT NULL,
			status TEXT NOT NULL DEFAULT 'pending',
			priority INTEGER NOT NULL DEFAULT 0,
			original_size INTEGER DEFAULT 0,
			target_resolution TEXT,
			ffmpeg_flags TEXT,
			error_message TEXT,
			video_codec TEXT NOT NULL DEFAULT 'libx265',
			audio_codec TEXT NOT NULL DEFAULT 'copy',
			crf TEXT,
			preset TEXT,
			tune TEXT,
			profile TEXT,
			container TEXT NOT NULL DEFAULT 'mkv',
			output_dir TEXT,
			delete_source INTEGER NOT NULL DEFAULT 0,
			keep_original_if_larger INTEGER NOT NULL DEFAULT 0,
			keep_extra_streams INTEGER NOT NULL DEFAULT 1,
			force INTEGER NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT (datetime('now')),
			updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
		)`,
	`CREATE TABLE IF NOT EXISTS job_reports (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			file_path TEXT NOT NULL,
			media_type TEXT NOT NULL,
			status TEXT NOT NULL,
			original_size INTEGER NOT NULL DEFAULT 0,
			encoded_size INTEGER NOT NULL DEFAULT 0,
			size_saved INTEGER NOT NULL DEFAULT 0,
			processing_time REAL DEFAULT 0,
			target_resolution TEXT,
			ffmpeg_flags TEXT,
			error_message TEXT,
			video_codec TEXT NOT NULL DEFAULT 'libx265',
			audio_codec TEXT NOT NULL DEFAULT 'copy',
			crf TEXT,
			preset TEXT,
			tune TEXT,
			profile TEXT,
			container TEXT NOT NULL DEFAULT 'mkv',
			output_dir TEXT,
			delete_source INTEGER NOT NULL DEFAULT 0,
			keep_original_if_larger INTEGER NOT NULL DEFAULT 0,
			keep_extra_streams INTEGER NOT NULL DEFAULT 1,
			ffmpeg_command TEXT,
			created_at DATETIME NOT NULL DEFAULT (datetime('now'))
		)`,
	`CREATE TABLE IF NOT EXISTS app_config (
			config_key TEXT PRIMARY KEY,
			config_value TEXT
		)`,
}
